# Generated by Django 5.2 on 2025-04-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='boroughs/')),
                ('norm_rent', models.FloatField(blank=True, null=True)),
                ('norm_crime', models.FloatField(blank=True, null=True)),
                ('norm_youth', models.FloatField(blank=True, null=True)),
                ('norm_centrality', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
