# Generated by Django 5.2 on 2025-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borough', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borough',
            name='image_url',
        ),
        migrations.AddField(
            model_name='borough',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boroughs/'),
        ),
    ]
