# Generated by Django 5.2 on 2025-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borough', '0002_remove_borough_image_url_borough_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='avg_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borough',
            name='safety_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borough',
            name='youth_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
