# Generated by Django 5.2 on 2025-04-11 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borough', '0002_communityfeature_communityrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityrating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
