# Generated by Django 5.2 on 2025-04-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borough', '0003_borough_avg_rent_borough_safety_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borough',
            old_name='safety_score',
            new_name='norm_crime',
        ),
        migrations.RenameField(
            model_name='borough',
            old_name='youth_ratio',
            new_name='norm_youth',
        ),
        migrations.RenameField(
            model_name='borough',
            old_name='avg_rent',
            new_name='norm_rent',
        ),
    ]
