# Generated by Django 5.2 on 2025-04-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borough', '0004_rename_safety_score_borough_norm_crime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='norm_centrality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borough',
            name='norm_rent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
