# Generated by Django 5.2 on 2025-04-11 16:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borough', '0004_alter_communityrating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borough',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='boroughs/'),
        ),
    ]
