# Generated by Django 5.2 on 2025-04-12 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borough', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchQuestion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('choice', 'Choice'), ('boolean', 'Boolean'), ('text', 'Text'), ('number', 'Number')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MatchOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='recommender.matchquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserMatchAnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hash')},
            },
        ),
        migrations.CreateModel(
            name='UserMatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.usermatchanswerset')),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borough.borough')),
            ],
            options={
                'unique_together': {('answer_set', 'borough')},
            },
        ),
    ]
